# Generated by Django 2.1.3 on 2018-11-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name': 'Layer configuration'},
        ),
        migrations.AlterModelOptions(
            name='wmslayer',
            options={'verbose_name': 'WMS-Layer'},
        ),
        migrations.AlterModelOptions(
            name='wmsserver',
            options={'verbose_name': 'WMS-Server'},
        ),
        migrations.AddField(
            model_name='layer',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aap', to='wms.WMSLayer', verbose_name='WMS layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.WMSLayer', verbose_name='WMS layer'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='wms.Map', verbose_name='map'),
        ),
    ]
