# Generated by Django 2.1.3 on 2018-11-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20181116_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='layer',
        ),
    ]
