# Generated by Django 2.1.3 on 2018-11-07 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point

class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveydata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(5, 52), srid=4326, verbose_name='location'),
            preserve_default=False,
        ),
    ]
