# Generated by Django 2.1.3 on 2018-11-07 22:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0002_surveydata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='location'),
        ),
    ]
