# Generated by Django 2.1.3 on 2018-11-08 23:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0003_auto_20181107_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='survey',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='survey'),
        ),
    ]
