# Generated by Django 2.1.3 on 2018-11-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0004_auto_20181108_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='project',
            field=models.CharField(max_length=100, unique=True, verbose_name='project name'),
        ),
    ]
