# Generated by Django 2.1.3 on 2018-11-12 08:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0005_auto_20181109_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='survey',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='survey'),
        ),
    ]
