# Generated by Django 2.1.3 on 2018-11-16 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0006_auto_20181112_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='limit')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Class limit',
                'ordering': ('limit',),
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('layer', models.CharField(max_length=100, verbose_name='layer')),
            ],
            options={
                'verbose_name': 'Indicator',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='surveydata',
            options={'verbose_name': 'Survey'},
        ),
        migrations.AddField(
            model_name='surveydata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveydata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classlimit',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwt.Indicator', verbose_name='indicator'),
        ),
    ]
