# Generated by Django 2.1.3 on 2018-11-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0007_auto_20181116_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('minzoom', models.SmallIntegerField(blank=True, null=True, verbose_name='maxzoom')),
                ('maxzoom', models.SmallIntegerField(blank=True, null=True, verbose_name='minzoom')),
                ('opacity', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='opacity')),
            ],
            options={
                'verbose_name': 'Layer',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Map',
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='order')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwt.Layer', verbose_name='layer')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwt.Map', verbose_name='map')),
            ],
        ),
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=100, verbose_name='layername')),
            ],
        ),
        migrations.CreateModel(
            name='WMSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('url', models.URLField(default='http://gis.acaciadata.com/?map=/project/gwtool/GWtool.qgs', max_length=255, verbose_name='url')),
            ],
        ),
        migrations.AlterField(
            model_name='indicator',
            name='url',
            field=models.URLField(default='http://gis.acaciadata.com/?map=/project/gwtool/GWtool.qgs', max_length=255, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwt.WMSServer', verbose_name='WMS Server'),
        ),
        migrations.AddField(
            model_name='layer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwt.WMSLayer', verbose_name='layer'),
        ),
    ]
