# Generated by Django 2.1.3 on 2018-11-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwt', '0008_auto_20181116_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='map',
        ),
        migrations.RemoveField(
            model_name='wmslayer',
            name='server',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='MapLayer',
        ),
        migrations.DeleteModel(
            name='WMSLayer',
        ),
        migrations.DeleteModel(
            name='WMSServer',
        ),
    ]
