# Generated by Django 2.0.2 on 2018-11-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwt', '0009_auto_20181116_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='info',
            field=models.URLField(default='http://rat.acaciadata.com/info', help_text='URL for background information', verbose_name='info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlimit',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='gwt.Indicator', verbose_name='indicator'),
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='project',
            field=models.CharField(max_length=100, verbose_name='project name'),
        ),
    ]
